# Generated by Django 5.0.3 on 2024-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='card',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created',
        ),
    ]
